### PR TITLE
Rewrite Interact server in Tornado

### PR DESCRIPTION
**Pull request by SamLau95**
cc @papajohn

This PR takes Alvin's work in #9 and rewrites the server to use tornado for
actual multithreading.

I tested this locally by trying to clone two repos at once and it worked!

### CODE REVIEW

**Comment by SamLau95** [comment]
I'm inclined to merge this tonight and deploy on ds8 to test it out. Any thoughts?

**Comment by ryanlovett** [comment]
Awesome. Yes, we can test on ds8 tonight. When would be a good time? I can
simulate pulling via a handful of accounts at once.

Ryan

**Comment by ryanlovett** [comment]
Regarding the comments about porting the old configuration code, I suggest taking a look at traitlets, https://github.com/ipython/traitlets. It was created by the IPython team, most IPython and Jupyter projects use it, and it is straightforward to adopt IMO.

```
c = get_config()
c.Interact.somevar = "example.com"
c.Interact.mydict = [dict(name="ps1")]
c.Interact.mylist = [
    dict(id="foo", thing="Alpha"),
    dict(id="bar", thing="Beta"),
    dict(id="baz", thing="Gamma")
]
```

More info: https://traitlets.readthedocs.io/en/stable/
Some examples: https://ipython.org/ipython-doc/3/config/intro.html

**Comment by SamLau95** [comment]
Sometime tonight would work best. @ryanlovett if that works for you think you can test it out? I have some other responsibilities to get done tonight and I'd like to focus on those.

Let's leave the cleanup for a separate PR.

**Comment by ryanlovett** [comment]
Yes, I'll do it later in the evening unless ds8 activity is low in which
case I'll bump it up.

Ryan

**Comment by SamLau95** [comment]
@ryanlovett I got this working on ds8. The issue was that the socket URL wasn't getting constructed properly.

It's fixed in https://github.com/data-8/DS8-Interact/pull/10/commits/25db7d53361908dc97ddd01f4ebc532bb3b09be2

I'm merging this now. Will make the changes to jupyterhub-deploy too.

**Comment by ryanlovett** [comment]
Great!

**Pull request merged**
