### PR TITLE
Enable pulling from private Github repos

### PR DESCRIPTION
**Pull request by SamLau95**
Adds the `GITHUB_ORG` environment variable which contains an API key
allowing the server to pull private repos from data-8.

Also adds a `BASE_URL` environment variable which allows the master
branch to be deployed to both ds8 and data8.

Resolves data-8/connector-instructors#9 .

### CODE REVIEW

**Comment by deculler** [comment]
Sam,
  I'm trying to pull together a little example for this morning's connector
meeting.  What's require to make interact link work for an arbitrary public
link?

Not having a convenient repo within data8 I set up a public personal repo.
https://github.com/deculler/ds-connect
That gave me a chance to set up a nice clean gh-pages.

My test is to put the interact blank link in the index.html in the gh-pages
branch.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
Hey David, sorry for the late reply; right now the interact server is hardcoded to pull from data-8 repos.

I forked your repo to https://github.com/data-8/ds-connect so you can make links work with that for today since we don't have much time.

**Comment by SamLau95** [comment]
Eg. using links like

```
https://data8.berkeley.edu/hub/interact?repo=ds-connect&path=README.md
```

**Comment by deculler** [comment]
Ahh, while sitting class I got John to create cs-connector.  All of one
mind.  Two issues.

#1 These links all open up the clone of the repo rather than the file at
the end of the path.  Your example does this too.

#2 I discovered going through this with the connector instructors that
getting the very first notebook into their repo (without using the obvious
command line tools) was a pain.  Once we fix the path problem, we can
create an initial page in all the gh-pages branches that will eliminate
that problem.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by deculler** [comment]
This one give me the repo directory, not the file.  Is that what it does
for you?

**Comment by SamLau95** [comment]
Yup, for now. See data-8/connector-instructors#16

**Pull request merged**
